MicroFlowSideProj/Controllers/WatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MicroFlowSideProj.Models;

namespace MicroFlowSideProj.Controllers
{
    public class WatchController : Controller
    {
        //
        // GET: /Watch/
        EformsystemEntities db;

        public ActionResult Main() {
            using (db = new EformsystemEntities()) {
                var vm = db.A_SignCRRForm
                    .OrderByDescending(x => x.ReqDate)
                    .ToList();
                return View(vm);
            }
        }

        public ActionResult MailList(string SerialNumber) {
            if (string.IsNullOrEmpty(SerialNumber)) {
                return View("");
            } else {
                using (db = new EformsystemEntities()) {
                    var vm = db.v_MailList
                        .Where(x => x.FormSN == SerialNumber)
                        .OrderByDescending(x => x.CreateTime)
                        .ToList();
                    return View(vm);
                }
            }
        }

        public ActionResult MailBody(string mGuid) {
            if (mGuid != null) {
                using (db = new EformsystemEntities()) {
                    var email = db.A_MailList
                                    .Where(x => x.mGUID == mGuid)
                                    .SingleOrDefault();
                    return View(email);
                }
            } else {
                return View();
            }
        }

    }
}

MicroFlowSideProj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - MicroFlow Side Project.</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("MicroFlow Mail Checkor", "MailList", "Watch")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        您好，<span class="username">@User.Identity.Name</span>!
                    </section>
                   @* <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                            <li>@Html.ActionLink("關於", "About", "Home")</li>
                            <li>@Html.ActionLink("連絡", "Contact", "Home")</li>
                        </ul>
                    </nav>*@
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - MicroFlow Side Project</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>